### ISSUE TITLE
Run Now not working

### ISSUE THREAD

**Issue by ggedde** [johnbillion/wp-crontrol#33]
Not sure if this is related to #30 
However, for me the Run Now does not run my Task.  I have to wait for the time to lapse and then hit /wp-cron.php.  

I do get the Success message that the Run Now worked, but it doesn't get to my callback function.

**Comment by johnbillion** [comment]
Do you have `DISABLE_WP_CRON` defined?

I've been testing this functionality lately and haven't seen any problems.

**Comment by ngocphamm** [comment]
I think I'm seeing the same behavior. The weird thing is I have a task that should run hourly, and when it's about 30 mins remaining (until the task is scheduled to run), clicking "Run Now" works. It doesn't work when it's only about 15 mins left. It sounds weird but it's what I'm seeing...

**Comment by ggedde** [comment]
@ngocphamm Hmm, well the cron that I have been testing it on is set to 15min, so there might be some correlation there.

@johnbillion 
Yes, I have it defined, but set to false.
`define( 'DISABLE_WP_CRON', false );`
Why would that matter?  I would assume that clicking "Run Now" is like forcing the action() to run?
Are you saying that setting could have an effect on whether the "Run Now" would work?

**Comment by ngocphamm** [comment]
@johnbillion probably referred to https://github.com/johnbillion/wp-crontrol/issues/30, which apparently has a fix for that.

**Comment by bethshook** [comment]
I think I have the same problem. I have a cron event running every 15 mins and 'Run Now' seems to work in the first few minutes after the event has fired, but after that it is useless.

**Comment by montrealks** [comment]
Having the same issue

**Comment by johnbillion** [comment]
I've just released version 1.8 and while it doesn't directly fix this problem it does now give you an explicit error message when there's a problem running the event (as long as you're running WordPress 5.1 or later).

The root cause is whatever logic is inside WordPress core's cron system that prevents an event from being fired. Unfortunately the details of the failure don't get exposed and therefore WP Crontrol can't tel you anything about the error. I'm going to see if we can make some improvements to this error reporting in WordPress core and then a future version of WP Crontrol will be able to make use of it.
