### ISSUE TITLE
Cannot delete created cron

### ISSUE THREAD

**Issue by avagp** [johnbillion/wp-crontrol#61]
I have modified the time where the wc_admin_daily cron runs. From daily to every minute (i was testing something)

But the plugin changed the name of the task to: action_scheduler_run_queue

And now i cannot delete it:
![image](https://user-images.githubusercontent.com/11801254/118591459-30ee2400-b772-11eb-87bf-b79bfb6e911a.png)

It says, it cannot be found.

Would you help me delete this?

**Comment by johnbillion** [comment]
Events with short intervals can be problematic because they can run in between the time you load the screen and the time you press the Delete button.

If you reload the screen a few times and then delete the event when it shows something like 50+ seconds until it's due then you'll be able to delete it.

Nothing that WP Crontrol can do about this, unfortunately!
