### ISSUE TITLE
fatal error on update from 1.14 to 1.15

### ISSUE THREAD

**Issue by tharsheblows** [johnbillion/wp-crontrol#91]
Hi! The plugin gave me this error when I updated it from 1.14 to 1.15. It was deactivated and I'm running on php 7.4 and WP 6.1.1.

This is the error:
`PHP Fatal error: Uncaught Error: Call to undefined method Composer\\Autoload\\ClassLoader::setClassMapAuthoritative() in /nas/content/live/[site]/wp-content/plugins/wp-crontrol/vendor/composer/autoload_real.php:43\nStack trace:\n#0 /nas/content/live/[site]/wp-content/plugins/wp-crontrol/vendor/autoload.php(7): ComposerAutoloaderInitdbf095101a93cb72acf9efa892a78eaf::getLoader()\n#1 /nas/content/live/[site]/wp-content/plugins/wp-crontrol/wp-crontrol.php(52): ... `

The update worked when testing on a staging site. 

If you have any questions please ask! I don't need help with this issue. I wasn't quite sure where to report it to let you know in case it happens to someone else.

**Comment by johnbillion** [comment]
Thanks for the report and the sponsorship JJ! You're very kind.

One other user has reported this: https://wordpress.org/support/topic/fatal-error-in-plugin-version-1-15-0/ . It looks like it's caused by an ancient version (pre-1.0) of the Composer autoloader being used by another plugin on the site, and I'm not yet sure if there's a way around it.

If you could let me know the list of active plugins and their versions on the affected site that would be a help.

See also #89.

**Comment by johnbillion** [comment]
Is Composer used on the site at all? If so it might be the version of Composer on the server that's the problem -- `composer --version` will tell you the version number. Anything pre-1.0 is out of warranty I'm afraid.

If that's not the case then can you find out if any of the plugins on your site include a `vendor/composer/ClassLoader.php` file? If there is one and it doesn't include a `setClassMapAuthoritative()` method then that's the problematic file as it will have been generated by a pre-1.0 version of Composer.

**Comment by tharsheblows** [comment]
> ...can you find out if any of the plugins on your site include a vendor/composer/ClassLoader.php file? If there is one and it doesn't include a setClassMapAuthoritative() method then that's the problematic file as it will have been generated by a pre-1.0 version of Composer.

This is it! I have an old plugin from 2014 which used a very old version of Composer. I'll update that. I wonder why it caused an issue now.

**Comment by johnbillion** [comment]
The issue is that in WP Crontrol 1.15 I changed the Composer configuration to optimise the performance of the autoloader (c0eee066ba263d8eb74fa15e2e64d4ce324e22c5). The underlying `setClassMapAuthoritative()` method that Composer calls was added in 1.0 stable. In this case, the autoloader in your other plugin is firing first and loading the old pre-1.0 version of Composer's `ClassLoader` class which doesn't contain that method.

It's all a bit messy.
